# Generated by Django 4.1.7 on 2023-02-26 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relations',
            name='parent_karma',
            field=models.IntegerField(blank=True, default=0, editable=False, null=True),
        ),
    ]
