# Generated by Django 4.1.7 on 2023-02-27 05:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_alter_relations_parent_karma'),
    ]

    operations = [
        migrations.AlterField(
            model_name='relations',
            name='parent_karma',
            field=models.IntegerField(blank=True, db_index=True, default=0, editable=False, null=True),
        ),
    ]
