# Generated by Django 4.1.7 on 2023-02-28 00:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_branch_pre_karma'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='branch',
            name='pre_karma',
        ),
    ]
